## Studiedesign, arbeidskrav 4


I denne oppgaven skal jeg velge meg ut fem forskjellige studier og se på hvordan disse er gjennomført i sin helhet, ved styrker og svakheter i prosjektene. Studiene jeg har valgt og se på er studier som vurderer hvordan blokklegging av HIT-trening (Høy-intensitets trening) påvirker utholdenhetsprestasjonen til godt trente utholdenhetsutøvere. De ønsker og finne en måte og optimalisere den intensive treningen for og få mest mulig effekt ved og organisere det på en annen måte enn tidligere. I studiene sammenligner de ofte da perioder med fler HIT øker på en kortere periode istedenfor tradisjonell måte der HIT øktene er mer fordelt utover en gitt periode. 


Det har i nyere tid blitt mer og mer populært og se etter måter og optimalisere trening, spesielt for godt trente utøvere. Vi ser at for godt trente utøvere kreves det ekstra stimuli for at det skal skje endring, og ut ifra dette har blokk periodisering blitt populært. Dette er en måte og prioritere visse egenskaper over en viss tid samtidig som du vedlikeholder andre egenskaper. Du setter kroppen i en større utfordring, og med det store stimuliet krever du at kroppen gjør en endring og tilpasser seg (Issurin, 2008). 


Bent Rønnestad er en forsker som har sett mye på dette med blokkperiodisering av HIT-økter sammenlignet med tradisjonell oppbygning av HIT-økter. I studien til Rønnestad med overskriften «Blokkperiodisering av høyintensive intervaller gir bedre treningseffekter hos trente syklister» (Rønnestad, 2012) gjør de en studie som ser på forskjellene i effekten på to metoder for organisering av utholdenhetstrening. Den ene gruppen (forsøksgruppa) kjører første uken med fem HIT-økter, etterfulgt av tre uker med en HIT-økt per uke og hovedfokus på lavintensitetstrening. Kontrollgruppen fortsetter å kjøre tradisjonelt oppsett av periodiseringen, der de gjennomfører fire uker med to HIT-økter per uke kombinert med lavintensiv trening. De ser på faktorene som VO2max, Wmax (topp kraftutgang) og melkesyreterskel, sammenlignet med TRAD, hos trente syklisterVO2max, Wmax (topp kraftutgang) og melkesyreterskel, sammenlignet med kontrollgruppen, hos trente syklister. Hypotesen i artikkelen er at blokkperiodisering vil gi bedre tilpasninger enn tradisjonell periodisering hos trente syklister. Det samme gjelder hypotesen i studien (Rønnestad, 2022), som så på effekten av 6-dagers HIT-blokk på utholdenhetsprestasjonene til langrennsløpere, mål ved endringer i VO2max, maksimalt oksygenopptak, kraftutgang, og muskelkapillaritet. I likhet med den andre studien var hypotesen at gruppen som gjennomførte HIT trening i blokk ville forbedre sine prestasjonsindikatorer sammenlignet med gruppen som gjennomførte tradisjonell trening. 


En annen studie fra (Almquist, 2022) er hypotesen at blokkperiodisering av HIT-økter ville føre til større forbedringer i utholdenhetsprestasjoner enn tradisjonell trening, men i denne studien ble ikke hypotesen støttet da resultatene ikke stemte overens med dette. Mens i de to siste studiene jeg skal se på, hhv. (Breil, 2010) og (Solli, 2019) viser begge hypotesene til at de tror blokkperiodisering av HIT-trening vil føre til bedre utholdenhetsprestasjoner. Kort oppsummert kan vi se at de fleste studiene rammer inn forskingsproblemet som hypoteser, mens studien (Almquist, 2022) formulerer det som et utforskende spørsmål. Vi kan si at hypotesedrevet forskning passer godt når vi har lyst til og teste det spesifikke, målbare antakelser, mens mer spørsmål kan være bedre når forskninger er i en tidlig fase ved at det kan forskes bredere. Vi ser ofte i artiklene til Rønnestad at hypotesene ofte stemmer overens med resultatene og konklusjonen, noe som kan tyde på at forskeren kan ha endret på hypotesen etter at han har sett resultatene.


En årsak til logikken bak hypotesene er at bolkgruppene vil få en større mekanisk belastning over en kortere tidsperiode som er et sentralt signal til tilpasning. 


Når det gjelder studiedesignet har studiene (Rønnestad, 2022), (Rønnestad, 2012), (Breil, 2010) et randomisert kontrollert design. Randomiserte studier vil si at forsøkspersonene i gruppen er tilfeldig plassert i enten kontroll, eller blokktrenings-gruppen. Deltakere bør kvalifisere seg og gi samtykke for randomisering (Hulley, 2013). Det at studiene er randomiserte styrker studien ved at de utelukker påvirkningen av andre faktorer. Det minsker sjansen for skjevhet og gjør resultatene mer pålitelige. (Almquist, 2022) er ikke fullstendig randomisert kontrollert design da gruppene er uten strengt randomisert fordeling, dette kan være en svakhet ved studien. (Solli, 2019) skiller seg litt ut fra de andre studiene ved at den undersøker en enkelt forsøksperson. 

Når det gjelder utvalget i de forskjellige studiene ligger dette på rundt 20 forsøkspersoner, der de fordeler 50/50 mellom kontroll gruppe og intervensjonsgruppe. Studien til (Solli, 2019) er spesiell da det er en enkelmansstudie, og vi kan da si at den ikke representerer ett tilfeldig utvalg av populasjonen og gir derfor ikke et bilde på hele befolkningen, og resultatene kan være tilfeldige. I de resterende studiene kan vi si at det hadde vært fordelaktig og hatt ett større utvalg for og kunne si noe mer om det generelle i befolkningen. Ved færre forsøkspersoner kan det være større sannsynlighet for at resultatene har kommet ved en tilfeldighet. I alle studiene er det også plukket utøvere som er godt trente og på ett høyt nivå fra før, noe som vil si at resultatene kan sies og være relevante for denne gruppen personer, men ikke nødvendigvis for gjennomsnitt personen i populasjonen. I alle studiene måtte du være kvalifisert for og kunne være med, gjennom og ha visse resultater, dermed var det ikke et helt tilfeldig utvalg. 


Hvis vi ser på hvordan gjennomføringen var i studiene, brukte alle studiene pre- og post tester for å måle endringer i utholdenhetskapasitet, VO2max og andre fysiologiske parametere. I studiene (Rønnestad, 2022), (Rønnestad, 2012) og (Almquist, 2022) ble det gjennomført tester som testen både fysiologiske verdier og prestasjonsmål, prestasjonsmål er for eksempel en 20min/40min alt ut test der du ser om prestasjonen har blitt bedre. Det er en styrke og både se på fysiologiske faktorer og prestasjon, da vi kan få ett større bilde om det faktisk har ført til endringer. I (Solli, 2019) ble resultater i konkurranser brukt, dette er ett prestasjonsmål, men det er vanskelig og si om det er andre faktorer som skaper støy i forskingen og om vi faktisk klarer og finne ut hva som førte til endringer i resultater. 


De fleste studiene brukte t-tester og gjentatte målinger ANOVA for og se forskjeller i resultatene pre- og post intervensjonen. Ved bruk av dette kan man gjøre det mulig og se endinger i variabler er statistisk signifikante, og dermed støtter eller avkrefter hypotesene. Fire av studiene brukte også grafer og deskriptiv statistikk for å vise at treningsbelastningen mellom gruppene og utgangspunktet til forsøkspersonene var likt, med unntak av (Solli, 2019) som ikke hadde kontrollgruppe og derfor ikke noe om å sammenligne med. 

Når det gjelder resultater så konkluderte (Breil, 2010) med at HIT-gruppen forbedret VO2max med 6%, og relativ topp kraftutgang med 5,5% sammenlignet med kontrollgruppen. Det var ingen signifikant ending i alt ut test for noen av gruppene. I dette tilfellet støttet resultatene hypotesen ved at en intensiv HIT-bolk vil gi større forbedringer på VO2max og kraftutgang enn tradisjonell trening. (Rønnestad, 2012), (Rønnestad, 2022) viste begge studiene at gruppen som gjennomførte HIT-blokk trening hadde størst forbedringer på fysiologiske og prestasjonsmål. I begge tilfellene hadde Rønnestad støttet hypotesen. (Almquist, 2022) støttet ikke hypotesen ved at han ikke fant noe signifikante forskjeller mellom gruppene på sykkelprestasjon. 





Referanser:

Almquist, N, W., Eriksen, H, B., Wilhelmsen, M., Hamarsland, H., Ing, S., Sandbakk, Ø., Rønnestad, B, R., Skovereng, K., (2022). No disserencec between 12 weeks of block- vs. Traditional-periodized training i performance adaptions in trained cycklist. https://doi.org/10.3389/fphys.2022.837634

Breil, F. A., Weber, S, N., Koller, S., Hoppeler, H., Vogt, M. (2010). Block training periodization in alpine skiing: effects of 11-day HIT on VO2max and performance. 10.1007/s00421-010-1455-1

Hulley, S. B. (2013). Designing clinical research. Philadelphia, Wolters Kluwer/Lippincott Williams & Wilkins. https://tilda.tcd.ie/epidemiology-biostatistics-course/course-material/assets/Class2/Designingclinicalresearch_4th-edition.pdf

Issurin, V., 2008. Block periodization versus traditional training theory: a review. https://pubmed.ncbi.nlm.nih.gov/18212712/

Rønnestad, B. R., Bjerkrheim, K. A., Hansen, J., & Mølmen, K. S. (2022B). A 6-day highintensity interval microcycle improves indicators of endurance performance in elite cross-country skiers. Frontiers in Sports and Active Living, 4. https://doi.org/10.3389/fspor.2022.948127

Rønnestad, B, R., Hansen, J., Ellefsen, S., (2012) Block periodization of high-intensity aerobic intervals provides superior training effects in trained cyclists. https://doi.org/10.1111/j.1600-0838.2012.01485.x

Solli, G, S., Tønnessen, E., Sandbakk, Ø., (2019) Block vs. Traditional Periodization of HIT: Two Different Paths to Success for the World’s Best Cross-Country Skier, 10.3389/fphys.2019.00375


