---
output: html_document
editor_options: 
  chunk_output_type: console
---
Arbeidskrav 5

## Introduksjon:

Styrketrening er en viktig del av fysisk trening. Styrketrening er viktig i ett helseperspektiv ved å forebygge helsemessige utfordringer, dette kan for eksempel være muskelatrofi og svekket beinstyrke (Jespersen et al. 2003). Styrketrening har også vist seg og være viktig for og forbedre fysisk prestasjon (Rønnestad et al. 2014). Maksimal styrketrening avhenger hovedsakelig av muskelmasse, og det er en rekke faktorer man kan påvirke for og øke muskelmasse og muskelstyrke. (Raastad et al., 2010). Hvordan fordele treningsvolum, frekvens og motstand optimalt kan variere fra person til person, her spiller genetikken også inn. Treningsvolum i styrkesammenheng vil si antall sett per muskelgruppe i løpet av en uke. (Grgic et al. 2022). Fokuset rundt treningsvolum og styrketrening har i lengre tid vært ett stort tema. Det er vist i tidligere studier at ett lavt treningsvolum har ført til samme forbedringer som moderat treningsvolum. (Mitchell et al., 2012). Det kan spekuleres om det også er forskjeller når det gjelder godt styrketrente personer og dårlig styrketrente personer. Der det kan tyde på at det vil kreves ett større stimuli jo høyere nivå du er på. (Hughes, Ellefsen & Baar, 2018)

Selv om vi de aller fleste vet at styrketrening er viktig for helsa, er det mange personer som ikke gjennomfører regelmessig styrketrening. Begrensinger kan være kunnskap og evnen til og klare og sette av tid og prioritere det. trene (Choi et al., 2017) Derfor kan det være veldig hensiktsmessig og kunne finne ut mer rundt hvor mye stimuli og treningsvolum som faktisk kreves for og klare og få de adaptasjonene vi vil og de positive helsemessige gevinstene. Vi ser også at veldig mange i samfunnet nå blir mer og mer stillesittende, kan dette skape store problemer for helsa til mange personer i samfunnet. Studier viser også at muskelmasse og muskelstyrke reduseres spesielt ved økende alder, og rundt 50 år spesielt. Ved redusert styrke kan det føre til en rekke negative konsekvenser. Det at man som eldre mister muskelmasse er en naturlig prosess, men ved gjennomføring av styrketrening kan vi bremse denne utviklingen. (Marzetti et al 2006). 

Studiene Rhea et al. (2002) viste at gruppen som trente tre sett per øvelse hadde en større økning i muskelstyrke sammenlignet med den gruppen som trente med bare ett sett. Rønnestad et al. (2007) fant også ut at tre sett hadde bedre resultater enn gruppen som trente ett sett. Basert på studier som er gjort tidligere har denne studien som mål og se på forskjeller i muskelstyrke og muskelmasse der en gruppe trener med ett sett og en annen gruppe kjører tre sett. Det gjennomføres på beina. Resultatene kan finne ut hvordan forskjellige treningsvolumer påvirker styrken vår og muskelmassen. 


## Metode

#Deltagere

I studien ble det rekruttert 41 mannlige og kvinnelige deltagere. Det var noen krav som måtte dekkes for og kunne være med i studien, og det var at personene måtte være mellom 18-40 år og ikke røyke. Personene kunne ikke ha trent mer enn en ukentlig styrkeøkt det siste året, samtidig som de ikke skulle ha noe nedsatt muskelstyrke ved noen tidligere skader eller lignende. De skulle heller ikke gå på noe medisiner som kunne påvirke eller forstyrre effektene for treningen. Etter studien ble sju personer tatt vekk fra dataanalysen fordi de ikke hadde gjennomført tilstrekkelig av de obligatoriske øktene (85%) i treningsintervensjonen.  


## Intervensjon:

Perioden ble gjennomført i løpet av 12-ukers styrketrening av hele kroppen. Underekstremitetene ble trent unilateralt. Dette gjør det mulig å gjennomføre forskjellig treningsvolum på beina. Det ble gjennomført lavt volum på det ene beinet og moderat på det andre. Det ble gjennomført ett sett på beinet som hadde lavt treningsvolum, og tre sett på det med moderat treningsvolum. Det ble gjennomført treningsøkter to til tre ganger i uken.  Før hver treningsøkt gjennomførte personene en standardisert oppvarmingsprotokol. Den bestod av 5 minutter sykling på ergometersykkel, deretter ti repetisjoner av kroppsvektøvelser som push-ups, sit-ups, rygg hev og knebøy. Etter dette gjennomførte de ett sett med ti repetisjoner på 50% av 1RM (maksimalt løft) for hver styrkeøvelse. De tre beinøvelsene som ble gjennomført var unilateralt beinpress, leg-curl og kneekstensjon. Under teningsøkene hadde personene 90 til 180 sekunder pause mellom hver sett. Når det gjelder kosthold ble deltagerne bedt om å logge kosthold, samtidig som de fikk et standardisert energipåfyll, hhv. 0,16 g protein, 11,2 g karbohydrater og 0,5 g fett per kilo kroppsvekt. Dette var for og sikre at deltagerne fikk ett likt tilskudd av energi etter trening slik at ikke restitusjonen ble påvirket forskjellig på grunn av dette. 





Referanser

https://pubmed.ncbi.nlm.nih.gov/17052879/

https://pubmed.ncbi.nlm.nih.gov/14531367/

https://pubmed.ncbi.nlm.nih.gov/23914932/

https://pubmed.ncbi.nlm.nih.gov/33497853/

Mitchell, C. J., Churchward-Venne, T. A., West, D. W., Burd, N. A., Breen, L., Baker, S. K., & Phillips, S. M. (2012). Resistance exercise load does not determine training-mediated hypertrophic gains in young men. Journal of applied physiology (Bethesda, Md. : 1985), 113(1), 71–77. https://doi.org/10.1152/japplphysiol.00307.2012

Raastad, T., Paulsen, G., Refsnes, P. E., Rønnestad, B. R.& Wisnes, A. R. (2010). Styrketrening- i teori og praksis. Gyldendal Norsk forlag AS

Hughes, D. C., Ellefsen, S., & Baar, K. (2018). Adaptations to Endurance and Strength Training. Cold Spring Harbor perspectives in medicine, 8(6), a029769. https://doi.org/10.1101/cshperspect.a029769 

Choi, J., Lee, M., Lee, J. K., Kang, D., & Choi, J. Y. (2017). Correlates associated with participation in physical activity among adults: a systematic review of reviews and update. BMC public health, 17(1), 356. https://doi.org/10.1186/s12889-017-4255-2

