

# Philosophy of science


## Oppgave 1:

I vitenskapen bruker vi vitenskapelige argumenter som en måte for og rasjonelt og strukturelt måte kunne ha et bevis for og avkrefte eller bekrefte en påstand. Vitenskapelige argumenter er grunnleggende for vitenskapelige metode og den kritiske vurderingen av vitenskapelige påstander. Vi kan skille mellom induktive og deduktive argumenter. I deduktive argumenter er konklusjonen unngåelige dersom premissene er sanne, og argumentet er da deduktivt gyldig hvis det oppfyller dette kravet. Ett eksempel på et deduktivt argument kan være: Premiss 1: Alle mennesker er dødelige. Premiss 2: Sokrates var ett menneske. Konklusjon: Sokrates er dødelig. (Torstein Thurén, 2022, s.58-60)

Induksjon er en type vitenskapelig argumentasjon som trekker generelle konklusjoner ut fra spesifikke observasjoner, det vil si at vi trekker konklusjoner om fremtiden basert på observasjoner fra fortiden. Vi bruker denne måten og trekke konklusjoner på i både hverdagen og i vitenskapen. For eksempel kan vi bruke eksempelet om solen. Premiss 1: Sola har stått opp hver dag de siste 50 årene. Konklusjon: Solen vil stå opp i morgen. (Olav Vasserud, 2024) Selv om det er lett og si at det er logisk for oss at solen vil stå opp i morgen med det grunnlaget at den alltid har stått opp, men det dukker opp vitenskapelige spørsmål rundt dette. I det at vi konkluderer med at noe vil skje på grunn av at det har skjedd før viser til at vi legger til grunn at fremtiden skal være identisk med fortiden. Og kan vi da rettferdiggjøre induktive slutninger? (Torstein Thurén, 2022, s.52-53)

David Hume er en av de mest innflytelsesrike filosofene på 1700-tallet. Hume hevdet at det var umulig og rasjonelt rettferdiggjøre bruken av induksjon, og kom da opp med induksjonsproblemet. Humes problem med induktiv argumentasjon gikk ut på at troen om at fremtiden vil følge de samme mønstrene som i fortiden. Han sier at induksjon er en vanlig tilnærming, men vi kan ikke bevise at fremtiden skal være lik fortiden, noe som vil si at konklusjonen kan være sann, men det er ingen garanti. 
Humes kritikk handler om det faktumet at induktiv argumentasjon forutsetter ett skjult premiss, prinsippet om at fremtiden er lik fortiden. Dette prinsippet kan da ikke bevises rasjonelt. Hvis vi prøver å rettferdiggjøre dette ved bruk av induksjon havner vi i en sirkulær-argumentasjon ved at vi bruker induksjon for og rettferdiggjøre induksjon. Dette betyr at vi ikke rasjonelt kan bevise brukes av induksjon uten forutsette det vi prøver og bevise. 
For og komme med eksempler rundt dette bruker vi sola som tidligere i oppgaven. Vi sier at solen kommer til og stå opp i fremtiden, basert på at den har stått opp hver dag i fortiden. Selv om det er logisk og enkelt og si at sola vil stå opp i morgen basert på at den har gjort det i alle år, er det ingen garanti for at det skjer. Hume stiller spørsmålet: hvorfor skal vi anta at morgendagen skal følge tidligere mønstre? (Heine Alexander Holmen, 2024) 

En vanlig innvending mot Humes syn er at induksjon kan forsvares selv om det ikke er noe garanti for at konklusjonen er sann. Det er såpass fornuftig og tro at solen vil stå opp i morgen basert på at den alltid har gjort det. Det er fornuftig å stole på induksjonen for og kunne legge fremtidsplaner, selv om vi ikke kan garantere for fremtiden. Denne innvendingen er basert på erfaringer mer enn rasjonalitet. Vitenskapelige fremgang er i mange tilfeller basert på induksjon selv om vi ikke kan bevise at disse slutningene er riktige. Det baseres da på at det i flere tilfeller har stemt så godt at det er suksessen i praksis som gjør at vi tror på det. Det blir ett eksempel på at det er sant helt til det motsatte er bevist. 
Hume kan ha avvist denne innledningen ved og si at det foresatt ikke er en rasjonell begrunnelse for induksjon. Selv om induksjon er en praktisk måte og tenke på både i vitenskapen og i hverdagen, er det ikke samme som logiske eller rasjonelle argumenter. Vi vil hele veien ende opp med den samme sirkulær resonnementet som Hume kritiserte. For Hume er poenget at uansett hvor lettvint og logisk det er at fremtiden er lik fortiden, er det ingen garanti for og si dette. (Heine Alexander Holmen, 2024). 

Men for og kunne bringe verden fremover og i hverdagen vil det alltid være induktive argumenter. Dette vil skape mindre bekymringer enn at vi ikke kan planlegge morgendagen på bakgrunn av at vi ikke kan garantere at sola står opp fremover.


### Oppgave 2

Karl Popper var en av de mest innflytelsesrike vitenskapsfilosofiene, han utviklet teorien om falsifikasjonisme som et svar på Humes problem mot induksjon. Popper mente at problemet rundt induktiv argumentasjon kunne forsvares ved fokus på forfalskningen fremover verifisering. Popper mente at måle ved vitenskapen burde være å teste teorier ved og motbevise dem, isteden for og prøve og bekrefte teorier ved bruk av induksjon. Popper ville da utvikle falsifikasjonisme som ett svar på det han mente var svakhetene rundt Humes argumenter rundt den induktive argumentasjonen. Popper innså at det som Hume hadde påpekt var umulig å verifisere en vitenskapelig teori basert på begrenset antall observasjoner. (Knut Erik Tranøy, 2024)  
Popper ville heller at en god vitenskapelig teori måtte være falsifiserbar. Noe som vil si at den må testes på en måte som beviser at den er falsk. I eksempelet som er brukt i oppgaven med at sola vil stå opp i morgen med premisset at den alltid har gjort det, er det hittil umulig og bevise at det er falskt at det vil skje. Hvis en teori står imot mange forsøk på falsifikasjon blir det en mye større tillit til det selv om vi ikke kan være sikre på at den er endelig sann. (Torstein Thurén, S.67)

Popper foreslår en vitenskapelig syklus hvor man starter med en falsifiserbar hypotese, utleder presise prediksjoner som kan sjekkes empirisk, for så å falsifisere, lage ny hypotese, ny prediksjon, ny falsifisering også videre. (Olav Vasserud, 2024. S.16)

Et problem med Poppers falsifikasjonisme kan være at vi forkaster hypoteser som er for spesifikke og for enkelt falsifiserbar. For og ta ett enkelt eksempel fra hverdagen, kan premisset ved at brus ødelegger tannhelsen forkastes ved at vi finner eksempler der det falsifiseres, men svaret behøver ikke være unyttig, da vi i brorparten av tilfellene vil kunne si at store mengder brus vil ødelegge tannhelsen. 

Popper var selv klar over disse utfordringene, men understrekt at falsifikasjon ikke betyr at man umiddelbart må forkaste, teorier kan som nevnt tidligere da forberedes og tilpasses. Oppsummert hadde både Humes induksjonsproblem og Poppers falsifikasjonisme funnet gode filosofiske utfordringer ved vitenskapelig metode, og selv om det er vanskelig og gi en endelig løsning på induksjonsproblemet har Poppers falsifikasjonisme bidratt til noe som gjør det lettere og forstå og teste vitenskapelige teorier på. (Torstein Thurén, S. 68)












Referanser 

Alnes, Jan Harald: David Hume i Store norske leksikon på snl.no. Hentet 18. oktober 2024 fra https://snl.no/David_Hume

Olav Vasserud, (2024), Vitenskapsfilosofi dag 1.

Olav Vasserud, (2024), Vitenskapsfilosofi dag 2.

Tranøy, Knut Erik: Karl Popper i Store norske leksikon på snl.no. Hentet 18. oktober 2024 fra https://snl.no/Karl_Popper

Torstein Thurén, (2024). Vitenskapsteori for nybegynnere (3.utgave)
