project:
  type: book

book:
  title: "Mappeeksamen IDR4000"
  author: "Ole Conrad Burud"
  date: "2024-11-22"
  chapters:
    - index.qmd
    - 01-reliabilitet.qmd
    - 02-regression-models.qmd
    - 03-statistical-inference.qmd
    - 04-study-design.qmd
    - 05-repeated-measurements.qmd
    - 06-vitenskapsteori.qmd
    - 07-laboratory-report.qmd
    - references.qmd

bibliography: resources/bib-final.bib

format: html





