project:
  type: book

book:
  title: "Mappeeksamen IDR4000"
  author: "Ole Conrad Burud"
  date: "2024-11-21"
  chapters:
    - index.qmd
    - 01-reliabilitet.qmd
    - 02-regression-models.qmd
    - 03-statistical-inference.qmd
    - 04-study-design.qmd
    - 05-repeated-measurements.qmd
    - 06-vitenskapsteori.qmd
    - 07-laboratory-report.qmd
    - references.qmd

bibliography: resources/bib-final.bib

format:
  pdf: 
    keep-tex: true
    latex_engine: xelatex  # Bytt til xelatex for fontstøtte
    mainfont: "Times New Roman"  # Angi Times New Roman som hovedskrifttype
    include-in-header: 
      text:  |
        \usepackage{amsmath}
        \usepackage{float}
        \usepackage{pdflscape}
        \usepackage{afterpage}
        \usepackage{longtable}
        \usepackage[table]{xcolor}
        \usepackage{longtable}
        \usepackage{booktabs}


execute: 
  echo: false 
  warning: false 
  message: false
 